# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/offline/boxes/models/category/fields.yaml

# Model Class name
modelClass: Offline\Boxes\Models\Category

# Default redirect location
defaultRedirect: offline/boxes/categories

# Create page
create:
    title: backend::lang.form.create_title
    redirect: offline/boxes/categories/update/:id
    redirectClose: offline/boxes/categories

# Update page
update:
    title: backend::lang.form.update_title
    redirect: offline/boxes/categories
    redirectClose: offline/boxes/categories

# Preview page
preview:
    title: backend::lang.form.preview_title
