# ===================================
#  List Behavior Config
# ===================================

list: $/offline/boxes/models/collection/columns.yaml
modelClass: Offline\Boxes\Models\Collection
title: Manage Collections
recordUrl: offline/boxes/collections/update/:id?id=:category_id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showPageNumbers: true
showSetup: true
showSorting: true
defaultSort:
    column: name
    direction: asc
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
