# ===================================
#  Form Behavior Config
# ===================================

name: Collection
form: $/offline/boxes/models/collection/fields.yaml
modelClass: Offline\Boxes\Models\Collection
defaultRedirect: offline/boxes/collections

create:
    title: backend::lang.form.create_title
    redirect: offline/boxes/collections/update/:id
    redirectClose: offline/boxes/collections

update:
    title: backend::lang.form.update_title
    redirect: offline/boxes/collections
    redirectClose: offline/boxes/collections

preview:
    title: backend::lang.form.preview_title
